// Taj's COI Mods | TajsVisualsSettingsCatalog.cs
// Copyright (C) 2026 - 2026 Grzegorz Kaczmarski (TajemnikTV)
// All Rights Reserved.

using System.Collections.Generic;
using TajsCOI.Common.Settings;
using TajsCOI.Visuals.Features.Lighting;

namespace TajsCOI.Visuals
{
    internal static class TajsVisualsSettingsCatalog
    {
        internal const string ModId = "TajsVisuals";
        internal const string ModDisplayName = "Taj's Visuals";
        private const SettingFlags Flags = SettingFlags.Advanced;

        internal static readonly IReadOnlyList<SettingDescriptor> All = new[]
        {
            SettingDescriptor.Boolean(
                ModId,
                ModDisplayName,
                LightingSettings.EnableLighting,
                "Lighting controls",
                "Enables the reversible visual lighting policy.",
                false,
                "Lighting",
                flags: Flags),
            SettingDescriptor.Float(
                ModId,
                ModDisplayName,
                LightingSettings.IntensityMultiplier,
                "Sun intensity multiplier",
                "Multiplies the pristine vanilla sun intensity.",
                1.0,
                0.0,
                4.0,
                0.05,
                "Lighting",
                flags: Flags,
                componentRequirement: LightingSettings.EnableLighting),
            SettingDescriptor.Float(
                ModId,
                ModDisplayName,
                LightingSettings.AngleOffset,
                "Sun angle offset",
                "Visual yaw offset in degrees; simulation time and date are unchanged.",
                0.0,
                -180.0,
                180.0,
                1.0,
                "Lighting",
                flags: Flags,
                componentRequirement: LightingSettings.EnableLighting),
            SettingDescriptor.Float(
                ModId,
                ModDisplayName,
                LightingSettings.ShadowStrength,
                "Shadow strength",
                "Safe 0..1 multiplier applied to vanilla shadow strength.",
                1.0,
                0.0,
                1.0,
                0.05,
                "Lighting",
                flags: Flags,
                componentRequirement: LightingSettings.EnableLighting),
            SettingDescriptor.Boolean(
                ModId,
                ModDisplayName,
                LightingSettings.EnableCycle,
                "Visual day/night cycle",
                "Interpolates presentation-only phase lighting from the smooth simulation clock.",
                false,
                "Day and night",
                flags: Flags),
            SettingDescriptor.Boolean(
                ModId,
                ModDisplayName,
                LightingSettings.FixedLighting,
                "Fixed lighting phase",
                "Freezes the presentation phase at the current visual clock; simulation continues normally.",
                false,
                "Day and night",
                flags: Flags,
                componentRequirement: LightingSettings.EnableCycle),
            SettingDescriptor.Float(
                ModId,
                ModDisplayName,
                LightingSettings.DawnStart,
                "Dawn start",
                "Normalized presentation clock position.",
                0.20,
                0.0,
                1.0,
                0.01,
                "Day and night",
                flags: Flags,
                componentRequirement: LightingSettings.EnableCycle),
            SettingDescriptor.Float(
                ModId,
                ModDisplayName,
                LightingSettings.DayStart,
                "Day start",
                "Normalized presentation clock position.",
                0.30,
                0.0,
                1.0,
                0.01,
                "Day and night",
                flags: Flags,
                componentRequirement: LightingSettings.EnableCycle),
            SettingDescriptor.Float(
                ModId,
                ModDisplayName,
                LightingSettings.DuskStart,
                "Dusk start",
                "Normalized presentation clock position.",
                0.70,
                0.0,
                1.0,
                0.01,
                "Day and night",
                flags: Flags,
                componentRequirement: LightingSettings.EnableCycle),
            SettingDescriptor.Float(
                ModId,
                ModDisplayName,
                LightingSettings.NightStart,
                "Night start",
                "Normalized presentation clock position.",
                0.80,
                0.0,
                1.0,
                0.01,
                "Day and night",
                flags: Flags,
                componentRequirement: LightingSettings.EnableCycle),
            SettingDescriptor.Float(
                ModId,
                ModDisplayName,
                LightingSettings.DawnIntensity,
                "Dawn intensity",
                "Phase intensity multiplier layered over the base lighting policy.",
                0.65,
                0.0,
                4.0,
                0.05,
                "Day and night",
                flags: Flags,
                componentRequirement: LightingSettings.EnableCycle),
            SettingDescriptor.Float(
                ModId,
                ModDisplayName,
                LightingSettings.DayIntensity,
                "Day intensity",
                "Phase intensity multiplier layered over the base lighting policy.",
                1.0,
                0.0,
                4.0,
                0.05,
                "Day and night",
                flags: Flags,
                componentRequirement: LightingSettings.EnableCycle),
            SettingDescriptor.Float(
                ModId,
                ModDisplayName,
                LightingSettings.DuskIntensity,
                "Dusk intensity",
                "Phase intensity multiplier layered over the base lighting policy.",
                0.65,
                0.0,
                4.0,
                0.05,
                "Day and night",
                flags: Flags,
                componentRequirement: LightingSettings.EnableCycle),
            SettingDescriptor.Float(
                ModId,
                ModDisplayName,
                LightingSettings.NightIntensity,
                "Night intensity",
                "Phase intensity multiplier layered over the base lighting policy.",
                0.15,
                0.0,
                4.0,
                0.05,
                "Day and night",
                flags: Flags,
                componentRequirement: LightingSettings.EnableCycle),
            SettingDescriptor.Float(
                ModId,
                ModDisplayName,
                LightingSettings.DawnAngle,
                "Dawn angle",
                "Phase visual yaw offset in degrees.",
                -25.0,
                -180.0,
                180.0,
                1.0,
                "Day and night",
                flags: Flags,
                componentRequirement: LightingSettings.EnableCycle),
            SettingDescriptor.Float(
                ModId,
                ModDisplayName,
                LightingSettings.DayAngle,
                "Day angle",
                "Phase visual yaw offset in degrees.",
                0.0,
                -180.0,
                180.0,
                1.0,
                "Day and night",
                flags: Flags,
                componentRequirement: LightingSettings.EnableCycle),
            SettingDescriptor.Float(
                ModId,
                ModDisplayName,
                LightingSettings.DuskAngle,
                "Dusk angle",
                "Phase visual yaw offset in degrees.",
                25.0,
                -180.0,
                180.0,
                1.0,
                "Day and night",
                flags: Flags,
                componentRequirement: LightingSettings.EnableCycle),
            SettingDescriptor.Float(
                ModId,
                ModDisplayName,
                LightingSettings.NightAngle,
                "Night angle",
                "Phase visual yaw offset in degrees.",
                45.0,
                -180.0,
                180.0,
                1.0,
                "Day and night",
                flags: Flags,
                componentRequirement: LightingSettings.EnableCycle),
            SettingDescriptor.Float(
                ModId,
                ModDisplayName,
                LightingSettings.DawnShadow,
                "Dawn shadows",
                "Phase shadow-strength multiplier.",
                0.75,
                0.0,
                1.0,
                0.05,
                "Day and night",
                flags: Flags,
                componentRequirement: LightingSettings.EnableCycle),
            SettingDescriptor.Float(
                ModId,
                ModDisplayName,
                LightingSettings.DayShadow,
                "Day shadows",
                "Phase shadow-strength multiplier.",
                1.0,
                0.0,
                1.0,
                0.05,
                "Day and night",
                flags: Flags,
                componentRequirement: LightingSettings.EnableCycle),
            SettingDescriptor.Float(
                ModId,
                ModDisplayName,
                LightingSettings.DuskShadow,
                "Dusk shadows",
                "Phase shadow-strength multiplier.",
                0.75,
                0.0,
                1.0,
                0.05,
                "Day and night",
                flags: Flags,
                componentRequirement: LightingSettings.EnableCycle),
            SettingDescriptor.Float(
                ModId,
                ModDisplayName,
                LightingSettings.NightShadow,
                "Night shadows",
                "Phase shadow-strength multiplier.",
                0.35,
                0.0,
                1.0,
                0.05,
                "Day and night",
                flags: Flags,
                componentRequirement: LightingSettings.EnableCycle),
        };

        internal static void RegisterAll(ITajsSettings settings)
        {
            foreach (SettingDescriptor descriptor in All)
            {
                settings.Register(descriptor);
            }
        }
    }
}
